export Counter from './Counter'
export Product from './Product'
export Carts from './Carts'
export ProductDetail from './ProductDetail'
export NewDetail from './newDetail'
export Footer from './footer'